FILE_OFFSET = -DOFFSET64BIT
gfortran:
		( $(MAKE) all \
	"SFC = gfortran" \
	"SCC = gcc" \
	"FFLAGS = -O3 -m64 -ffree-line-length-none -fdefault-real-8 -fconvert=big-endian -ffree-form" \
	"CFLAGS = -O3 -m64" \
	"LDFLAGS = -O3 -m64" \
	"CORE = $(CORE)" \
	"CPPFLAGS = $(MODEL_FORMULATION) -DUNDERSCORE -m64 $(FILE_OFFSET) $(ZOLTAN_DEFINE)" )
